# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DVi8JTYr_av8RYSGsvzrPwJwHH8Uudjn
"""

import pandas as pd
import matplotlib.pyplot as plt


# STEP 1: LOAD DATA

trades = pd.read_csv("historical_data.csv")
sentiment = pd.read_csv("fear_greed_index.csv")

# STEP 2: CLEAN COLUMN NAMES

trades.columns = trades.columns.str.strip()
sentiment.columns = sentiment.columns.str.strip()


# STEP 3: FIX TRADES DATE

trades['Timestamp IST'] = pd.to_datetime(
    trades['Timestamp IST'],
    format="%d-%m-%Y %H:%M",
    errors='coerce'
)

# Normalize to same datetime format
trades['date'] = trades['Timestamp IST'].dt.normalize()

# STEP 4: FIX SENTIMENT DATE

sentiment['date'] = pd.to_datetime(
    sentiment['date'],
    errors='coerce'
).dt.normalize()


# STEP 5: MERGE DATA

merged = pd.merge(trades, sentiment, on='date', how='inner')

print("Merged rows:", len(merged))


# STEP 6: FIX COLUMN NAMES

merged.rename(columns={
    'Closed PnL': 'closedPnL',
    'Side': 'side',
    'classification': 'Classification'
}, inplace=True)

# STEP 7: ANALYSIS


# Average PnL
avg_pnl = merged.groupby('Classification')['closedPnL'].mean()
print("\nAverage PnL:\n", avg_pnl)

# Total PnL
total_pnl = merged.groupby('Classification')['closedPnL'].sum()
print("\nTotal PnL:\n", total_pnl)

# Trade Count
trade_count = merged.groupby('Classification')['closedPnL'].count()
print("\nTrade Count:\n", trade_count)

# BUY vs SELL
buy_sell = merged.groupby(['Classification', 'side'])['closedPnL'].mean()
print("\nBuy vs Sell:\n", buy_sell)


# STEP 8: VISUALIZATION

# Avg PnL graph
avg_pnl.plot(kind='bar')
plt.title("Average PnL by Market Sentiment")
plt.ylabel("Average PnL")
plt.xlabel("Sentiment")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

# Total PnL graph
total_pnl.plot(kind='bar')
plt.title("Total PnL by Market Sentiment")
plt.ylabel("Total PnL")
plt.xlabel("Sentiment")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

# BUY vs SELL graph
buy_sell.unstack().plot(kind='bar')
plt.title("Buy vs Sell Performance by Sentiment")
plt.ylabel("Average PnL")
plt.xlabel("Sentiment")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()